AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Architecture for performing CRUD operation in DynamoDB via
  Lambda and Api-Gateway.
Transform: AWS::Serverless-2016-10-31
Resources:
  dynamoDBCRUDWithApiGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dynamoDB_crud_with_api_gateway
      Handler: dynamoDB_crud_with_api_gateway.lambda_handler
      Runtime: python3.9
      Description: Used to perform crud operatoin using api_gateway
      Role:
        Fn::GetAtt:
        - dynamoDBCRUDWithApiGatewayRole
        - Arn
      CodeUri: s3://cf-templates-ocgcqdtj6f5h-us-east-2/1b4465ea1bf29554e91d5824ffb357e5
  dynamoDBCRUDWithApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dynamoDBCRUDWithApiGatewayRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
      - PolicyName: customLambdaAccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: IAMAccess
            Effect: Allow
            Action:
            - iam:*
            Resource:
            - arn:aws:iam::*:role/*
          - Sid: DynamoDBIndexAndStreamAccess
            Effect: Allow
            Action:
            - dynamodb:GetShardIterator
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            Resource:
            - arn:aws:dynamodb:us-east-2:699377644038:table/*/index/*
            - arn:aws:dynamodb:us-east-2:699377644038:table/*/stream/*
          - Sid: DynamoDBTableAccess
            Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:ConditionCheckItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            Resource:
            - arn:aws:dynamodb:us-east-2:699377644038:table/*
          - Sid: DynamoDBListStreamsAccess
            Effect: Allow
            Action:
            - dynamodb:ListStreams
            Resource:
            - arn:aws:dynamodb:us-east-2:699377644038:table/*/index/*
            - arn:aws:dynamodb:us-east-2:699377644038:table/*/stream/*
          - Sid: DynamoDBDescribeLimitsAccess
            Effect: Allow
            Action:
            - dynamodb:DescribeLimits
            Resource:
            - arn:aws:dynamodb:us-east-2:699377644038:table/*
            - arn:aws:dynamodb:us-east-2:699377644038:table/*/index/*
  ApiGatewayStack:
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cf-templates-ocgcqdtj6f5h-us-east-2/94a06fc5bcaa697c3b7e76955c1194e1.template
      Parameters:
        dynamoDBCRUDWithApiGatewayFunctionArn:
          Fn::GetAtt:
          - dynamoDBCRUDWithApiGatewayFunction
          - Arn
  DynamoDBStack:
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cf-templates-ocgcqdtj6f5h-us-east-2/c671e86a5ea2f873fd2b63c9167cd2a0.template